
DEF STARS_VERSION	EQUS "1.03"
DEF STARS_STATUS 	EQUS "BETA"

DEF STARS_ISCMPLETE	EQUS "NO"

DEF STARS_PRODNAME 	EQUS "#MON STARS"
DEF STARS_PRODNAME2	EQUS "POKEMON STARS"

DEF STARS_DEMONUM	EQUS "1"
DEF STARS_ISDEMO	EQU  FALSE
DEF TITLE_SHOWVER   EQU  TRUE

DEF RIVAL			EQUS "BLUE"
