
DEF STARS_VERSION	EQUS "1.01"
DEF STARS_STATUS 	EQUS "BETA"

DEF STARS_ISCMPLETE	EQUS "NO"

DEF STARS_PRODNAME 	EQUS "#MON STARS"
DEF STARS_PRODNAME2	EQUS "POKEMON STARS"

DEF RIVAL			EQUS "BLUE"

DEF TITLE_SHOWVER   EQU  TRUE
