
DEF STARS_VERSION		EQUS "1.07"
DEF STARS_STATUS 		EQUS "DEMO"

DEF STARS_ISCMPLETE		EQUS "NO"

DEF STARS_PRODNAME 		EQUS "#MON STARS"
DEF STARS_PRODNAME2		EQUS "POKEMON STARS"
DEF STARS_PRODNAME3		EQUS "POKÉMON STARS"

DEF STARS_DEMONUM		EQUS "2"
DEF STARS_ISDEMO		EQU  FALSE
DEF TITLE_SHOWVER 		EQU  TRUE

DEF RIVAL	 			EQUS "BLUE"

DEF SPHERE_MAPWIDTH		EQU  16
DEF SPHERE_MAPHEIGHT	EQU  16
